<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="zhouruideMacBook-Pro-2.local" ignored="0" name="充值接口" tests="6" failures="4" timestamp="31 一月 2021 15:18:31 GMT" time="3.234" errors="0">
  <testcase name="test" time="0.08" classname="cases81.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.RechargeCase.test(RechargeCase.java:49)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.072" classname="cases81.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.RechargeCase.test(RechargeCase.java:49)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.084" classname="cases81.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.RechargeCase.test(RechargeCase.java:49)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.147" classname="cases81.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.RechargeCase.test(RechargeCase.java:49)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.76" classname="cases81.RechargeCase"/>
  <testcase name="test" time="1.912" classname="cases81.RechargeCase"/>
</testsuite> <!-- 充值接口 -->
