<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="zhouruideMacBook-Pro-2.local" ignored="0" name="登录接口" tests="6" failures="4" timestamp="31 一月 2021 15:18:28 GMT" time="0.728" errors="0">
  <testcase name="test" time="0.094" classname="cases81.LoginCase"/>
  <testcase name="test" time="0.072" classname="cases81.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.LoginCase.test(LoginCase.java:36)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.133" classname="cases81.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.LoginCase.test(LoginCase.java:36)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.112" classname="cases81.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.LoginCase.test(LoginCase.java:36)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.134" classname="cases81.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [PASSED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at cases81.LoginCase.test(LoginCase.java:36)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.083" classname="cases81.LoginCase"/>
</testsuite> <!-- 登录接口 -->
